version: '3.6'

services:
    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
            CORS_ALLOWED_ORIGINS: "https://local.mercure.wip"
            ALLOW_ANONYMOUS: 1
            SERVER_NAME: ":80"
            MERCURE_EXTRA_DIRECTIVES: |-
                cors_origins "https://local.mercure.wip"
                anonymous
        ports:
            - '80:80'
            - '443:443'
            - '20019:2019'